alertlogic/nepal-core

- package.json
- src/search-client/parser/operator.types.ts
- test/search-client/sqx.spec.ts
- Allow automatic property/value filter extraction
- Allow automatic aggregations based on loaded data, and calculations of
pre- and post- filter summations
Should allow much of the "customized" behavior of the notification
cardstack views to be collapsed back into the underlying cardstack
model, while at the same time extending the cardstack to handle more
common use cases out-of-the-box.
- Also includes one or two changes to route types
> US000000 - Cardstack Revisions

- package.json
- src/client/al-api-client.ts
adding option return types on .get .post etc
so we can stop doing  return await client.get() as Something
> adding generic return types

- src/search-client/parser/operator.types.ts
[ENG-4037](https://alertlogic.atlassian.net/browse/ENG-4037): Correlation rule doesn't honor search string for CIDR_MATCH
Before:
After:
> ENG-4037 - Correlation rule doesn't honor search string for CIDR_MATCH

- package.json
- src/common/cardstack/al-cardstack-view.ts
https://alertlogic.atlassian.net/browse/ENG-5057
- Allow for multiple filters to be activated at once on cardstack view
> ENG-5057: cardstack support multiple active filters to be applied at once

- package.json
- src/client/al-api-client.ts
- src/client/events/index.ts
- src/client/index.ts
- src/client/types/index.ts
- src/common/utility/al-trigger.types.ts
- src/search-client/search-client.v2.ts
- src/search-client/search-stylist-client.ts
- src/session/al-session.ts
- test/session/al-session.spec.ts
- Updated trigger types to handle event typing of callback more
reasonably
- Added logic to only add X-AIMS-Auth-Token for appropriate API calls
- Refactored client types to make APIRequestParams available separately
- Fixed session test
> Refactor to support BaseAPIClient traffic (v1.0.27)

- package.json
- src/common/locator/al-navigation.types.ts
Expands `AlExperienceMapping` to include an optional set of "triggers"
that can be used to determine whether an experience should be available
under certain fixed conditions -- by environment, account, and time.
> ENG-7117 - Experience Flag Type Support

- package.json
- src/client/al-api-client.ts
- src/common/utility/json-utilities.ts
- src/session/al-session.ts
- test/common/json-utilities.spec.ts
- Replace instances of Object.assign in AlApiClient and AlSession with `deepMerge()`
- Tweaked `deepMerge` to preserve arrays
- Tweaked unit tests
- Removed verbose logging
> ENG-0000 - Plan D for IE11

- package.json
- src/client/al-api-client.ts
- src/client/types/index.ts
- src/common/locator/al-locator.types.ts
- src/common/utility/error-utilities.ts
- src/session/al-session.ts
- test/client/al-api-client.spec.ts
- test/search-client/sqx.spec.ts
- test/session/al-session.spec.ts
- Added `target_endpoint` property to APIRequestParams, which allows
caller to indicate an arbitrary endpoint key for base URL resolution
regardless of service_stack or service_name
- Added documentation for how endpoint resolution logic works
- Added AETuner API to list of default-authenticated service stacks
- Removed a bunch of unnecessary logging
> ENG-0000 - Version 1.0.54

- package.json
- src/client/al-api-client.ts
Why was it set to 1 minute in the first place?
> ENG-0000 - Remove Default XHR Timeout

- package.json
- src/client/al-api-client.ts
- test/client/al-api-client.spec.ts
Use of `deepMerge` to apply specific request configurations with default
values was trashing FormData instances.  Replaced with a shallow merge
algorithm in AlApiClient.
> ENG-0000 - Fixed FormData payload issue

- package.json
- src/common/forms/types.ts
in https://alertlogic.atlassian.net/browse/ENG-14639 the field payload does not require label
> ENG-14639: making label optional in forms

- package.json
- src/common/cardstack/al-cardstack-view.ts
Bypass local filtering of entities when the given filter is set to `remote: true` since filtering will already have been performed by the backend
> ENG-0000: cardstack local filtering logic update

- package.json
- src/common/cardstack/al-cardstack-view.ts
Local pagination is fundamentally broken in cardstack currently since it's not correctly being controlled by the `localPagination` property in `AlCardstackCharacteristics`!
> 1.0.71 - remove redundant localPagination prop in AlCardstackView

- package.json
- src/session/events/events.ts
- src/session/utilities/al-conduit-client.ts
Adds an event type and dispatch handler for external trackable events in
AlConduitClient.
https://alertlogic.atlassian.net/browse/ENG-16075
> ENG-16075 - Defender Javascript GA Metrics

- package.json
- src/common/cardstack/al-cardstack-view.ts
Recently detected an issue in our cardstack views with local pagination enabled that the initial display of rendered cards is not actually being limited to the `itemsPerPage` amount.
This issue is specific to a `sortingBy` value being present AND `localPagination` set to true.
**Current Behaviour:**
Consider a cardstack configured with localPagination=true, a sortingBy property set, and the itemsPerPage property left at its default value of 50. Also consider that and 100 rows of data is returned
In the start() routine in al-cardstack-view:
- `applySortBy` is invoked where a `sortingBy` condition is present
- in this method, the final line invokes `applyFiltersAndSearch`
- this in turn calls `startPagination`
- and this results in `this.cards` getting set to 50 items correctly
- back to …
> ENG-16870: fix for initial local pagination calculation in al-cardstack-view

- package.json
- src/common/errors/al-error.types.ts
- src/common/utility/al-cabinet.ts
- src/error-handler/al-error-handler.ts
- src/error-handler/index.ts
- src/index.ts
- Bumped version to 1.0.81
- Added a `touch` method to AlCabinet to retain a cached item with an
updated TTL.
- Added an AlErrorHandler class to normalize errors of various types
into a known form.
> ENG-0000 - Miscellaneous Enhancements

- package.json
- src/client/al-api-client.ts
- src/common/utility/al-cabinet.ts
- src/configuration/al-runtime-configuration.ts
- src/configuration/index.ts
- src/error-handler/al-error-handler.ts
- src/index.ts
- src/session/al-session.ts
- src/session/events/events.ts
- src/session/utilities/al-session-detector.ts
- test/session/al-session-detector.spec.ts
- test/session/al-session.spec.ts
- Bumps version to 1.0.84
- Adds support for using gestalt endpoints to create, check, and
terminate AIMS sessions
- Adds a configuration management to be shared by downstream services
- Removes all things FOXy -- great idea, bad timing.
> ENG-0000 - Gestalt Session Management

- package.json
- src/session/utilities/al-conduit-client.ts
- test/session/al-conduit-client.spec.ts
Updated AlConduitClient to target integration environment when being
used in a development environment.  This essentially removes the need
for portero to be run locally in development mode.
> ENG-0000 - Development Conduit

- karma.conf.js
- package.json
- src/aims-client/aims-client.ts
- src/aims-client/aims.schematics.ts
- src/client/al-api-client.ts
- src/client/common.schematics.ts
- src/client/types/index.ts
- src/common/errors/al-error.types.ts.backup
- src/common/forms/types.ts
- src/common/locator/al-route.types.ts
- src/common/utility/al-validation.types.ts
- src/common/utility/index.ts
- src/configuration/al-runtime-configuration.ts
- src/session/al-session.ts
- src/session/utilities/al-session-detector.ts
- test/common/al-errors.spec.ts
- test/common/al-validation.spec.ts
- test/session/al-session-detector.spec.ts
- test/session/al-session.spec.ts
- Added tv4 dependency.
- Added AlJsonValidator utility class, which does the work of resolving
dependent schemas and invoking tv4.
- Added support in AlDefaultClient for validation response against a
given schema, from a given set of providers.
- Added default schema providers for limited AIMS and common types.
- Added unit tests, and fixed some broken ones that never should have
worked in the first place.
- Ground my teeth to nubs
- Bumped version to 1.0.90
> ENG-19821 - Built-in JSON Validation

- package.json
- src/session/al-session.ts
AlSession exposes three different authentication methods --
username/password, session token/mfa verification code, and token -- and
there is a longstanding bug that prevents the token variant from working
properly.  At long last, that bug is squished.
> ENG-0000 - Fix defect when authenticating via AIMS Token

- package.json
- src/common/locator/al-route.types.ts
Adds a property to route definitions that allows the schema to indicate
which instance of a given route should be activated when there are
multiple possible matches.
In practice, this satisfies a need created by the Notifications/v4
feature, which has multiple routes referring to the same locations in
console.account.
> ENG-0000 - Support Primary/Inert Activation Modes

- src/aims-client/types/types.ts
- src/configuration/al-runtime-configuration.ts
- Added expiration threshold property to `AIMSAccount` interface
- Added a `setContext()` convenience method to `AlRuntimeConfiguration`
- Changed some mixed 2/4 indenting to consistent 4, because arggggh
> ENG-0000 - Session Idle Timeout

- package-lock.json
- src/client/al-api-client.ts
- src/client/index.ts
- src/common/navigation/al-locator.types.ts
- src/common/utility/al-mutex.ts
- src/common/utility/index.ts
- src/session/types/types.ts
- test/client/al-api-client.spec.ts
- Adds a simple promise-driven mutex class
- Use mutexes to enforce one endpoint lookup at a time
- Divided handling of default and residency-aware endpoint lookups
- Refactored to use native async/await more gracefully
- Totally replaced the way that endpoint dictionary is cached
> ENG-0000 - endpoint handling refactor

- package.json
- src/session/al-session.ts
Added AlLocation.MDRAPI to the list of "authenticated stacks" that
should automatically receive an X-AIMS-Auth-Token if there is an active
session.
Added a sardonic warning note.
> ENG-0000 - AlLocation.MDRAPI Authentication

- package.json
- src/session/al-session.ts
Previously, this method only resolved as ready after at least one
session detection cycle had been completed.  This could cause a timeout.
The logic has been revised to resolve if either all session detection
cycles are complete or none are in flight.
> ENG-0000 - Tweaked AlSession.ready()

- package.json
- src/aims-client/aims-client.ts
- src/client/al-api-client.ts
- src/session/al-session.ts
- src/session/utilities/al-session-detector.ts
- src/subscriptions-client/types/al-subscription.types.ts
Fixes state ambiguity during application bootstrap.
- Restoration of session state during AlSession constructor is *no
longer delayed* using setTimeout.  This was allowing session detection
to start before the state could be reconstituted.
- Restoration of session state from local/persisted data now blocks
session detection -- no more overlapping calls to `setActingAccount()`
- Session detector tracks changes to the acting account and
synchronizes them to conduit's stored session
Also a few nice to haves:
- Removed `retry_count` from AIMS and subscriptions calls; they just
aren't useful.
- Added a `toArray()` utility method to `AlEntitlementCollection`
- Captured complete AxiosResponse in lastError when an error occurs
> ENG-0000 - Hotpotatofix/v1.0.116

- package-lock.json
- package.json
Updates karma (because, bad karma) to latest, implicitly removing the dependency on
xmlhttprequest-ssl (required by socket.io), which had a severe vulnerability.
> ENG-0000 - Update Karma

- package.json
- src/common/errors/al-error.types.ts
- src/error-handler/al-error-handler.ts
- src/session/al-session.ts
- Added an AlWrappedError which provides human-friendly text for an
underlying error of unknown type.
- Updated `AlSession.getManagedAccounts()` to accept an optional
accountId parameter.
- Bumped version to 1.0.126
> ENG-26782 - Support for Redirection

- package.json
- src/aims-client/aims-client.ts
- src/session/utilities/al-session-detector.ts
Added a method to AIMSClient to allow setting the session idle threshold.
Also fixed a condition (that mostly effected the design library's
playground application) where a nasty error prints out if auth0 isn't
found.
> ENG-0000 - Session Idle

- package.json
- src/session/utilities/al-authentication.utility.ts
- src/session/utilities/al-conduit-client.ts
- src/session/utilities/al-session-detector.ts
- test/session/al-session-detector.spec.ts
Added logic to session detection to
1.  Query conduit for a session before querying gestalt or auth0
2.  Detect when conduit responds with a different token, and apply
it to the current session.
3.  Bumped version to 1.0.32
The intention here is to guarantee that the newest authentication token
is always propagated, and older ones are not persisted.
> ENG-0000 - Fix Expired Token Retention

- package.json
- src/session/utilities/al-session-detector.ts
Adds a `detectionComplete` method to AlSessionDetector, allowing a
caller to wait for session detection to finish without starting a
detection cycle.
> ENG-0000 - Session Detection Promise

- package.json
- src/session/al-session.ts
- src/session/utilities/al-authentication.utility.ts
- src/subscriptions-client/subscriptions-client.ts
Adds more graceful handling for cases where authentication succeeds but
account resolution does not.  In practice, this case concerns a user
account without any roles: authentication succeeds, but both
subscriptions/entitlements and aims/accounts lookups return a 403.
Also, removes retry from subscriptions/v1/entitlements endpoint.
VTT case here: https://alertlogic.atlassian.net/browse/VTT-3207
> ENG-0000/VTT-3207 - Authentication Without Roles

- package.json
- src/client/al-api-client.ts
- src/session/al-session.ts
The only API call in the entire IWS stack is the AIMS authenticate call
-- no other API relies on cookies or `Authorization` headers for any of
their work.  Unfortunately, yarp allows Access-Control-Allow-Credentials
for all endpoints, which is *technically* a vulnerability (Red Siege
identified it as a Low Criticality vulnerability, and Platform Services
and I agree it doesn't constite a real active threat).  To get it off of
our audit results, we will update the UI to use
`Access-Control-Allow-Credentials: true` ONLY for authentication
requests, and `Access-Control-Allow-Credentials: false` for all other
requests.  After the UI is fully updated, yarp will be updated to
disable credentials for all but the authentication endpoint.
Updated version to 1.0.136.
> ENG-28315 - Normalize XHRHttpRequest.withCredentials

- package.json
- src/client/al-api-client.ts
- src/common/errors/al-error.types.ts
Added two exception types, one for 503/service unavailable and one for
504/gateway timeout.
Updated `AlDefaultClient` to recognize timeout errors and convert them
into `AlGatewayTimeoutError` instances.
Bumped version to 1.0.139.
> ENG-0000 - @al/client interceptor for gateway timeouts

- package-lock.json
- package.json
This version is consistent with minimum requirements for later versions
of angular build tools, but should still be backwards compatible.
> ENG-0000 - Bump axios version

- package.json
- src/configuration/al-runtime-configuration.ts
- src/session/utilities/al-conduit-client.ts
- test/session/al-conduit-client.spec.ts
Adds a headless option to `AlRuntimeConfiguration`.
Cleans up several places with unguarded references to `document`.
> ENG-0000 - Headless Mode

- package.json
- src/common/navigation/al-locator.types.ts
https://alertlogic.atlassian.net/browse/ENG-33432
- This will ensure no redirect happens in magma when changing residency (between EMEA -> US and vice versa)
- For both acting account and datacenter (region) selections
> ENG-33432: fix prod uri locations for magma to .com variants

- package.json
- src/client/al-api-client.ts
- src/client/index.ts
- src/client/types/index.ts
- src/configuration/al-runtime-configuration.ts
Added configuration option to allow gestalt session proxying to work
through any application, based on configuration.
Also added a simple interception/error simulation mechanism to our API
Client.  This makes it possible to do something like this:
```
import { AlDefaultClient, randomAPIFailure } from '@al/core';
AlDefaultClient.setInterceptionRules( randomAPIFailure( 10 ) );
```
This will cause 10% of non-session-essential endpoints to fail with a
random error code.  It is also possible to use custom matchers and data,
i.e.,
```
import { AlDefaultClient, randomAPIFailure } from '@al/core';
AlDefaultClient.setInterceptionRules( [
{
method: "GET",
test: /\/applications\/v2\/[0-9]+/something/,
status: 200,
data: {
here: "any mock data you want"
}
},
{
method: "*",
test: …
```
> ENG-0000 - Magma Authentication Proxy

- package.json
- src/client/al-api-client.ts
Flaw was causing `undefined` parameter values to throw an
unhandled Exception instead of simply excluding that parameter from
expression.
> ENG-0000 - Fixed Flaw in AlApiClient.normalizeQueryParams

- package-lock.json
- package.json
Axios versions from 0.21.2 and higher change the way that response
interception promises are wrapped, such that additional tasks are queued
reliably.  Unfortunately, this breaks some of our testing infrastructure
for other projects.
> ENG-0000 - Axios Downgrade

- package-lock.json
- package.json
- src/client/al-api-client.ts
- test/client/al-api-client.spec.ts
Cargo service has recently been updated to be deployed to multiple residencies and so the UI now needs to construct calls to cargo based on the current active residency
> ENG-0000: add cargo service to residency aware whitelist

- package.json
- src/client/al-api-client.ts
Made the `resolveResidencyAwareEndpoints` method public instead of
protected, allowing it to be invoked explicitly where necessary.
> ENG-0000 - Expose Residency-Specific Resolver Method

- package.json
- src/subscriptions-client/types/al-subscription.types.ts
- test/subscriptions-client/entitlements.spec.ts
Added support for the wildcard entitlement '*', which always evaluates
to `true`.  This construct is used heavily by protected views in various
apps.
> ENG-0000 - Wildcard Entitlement

- package.json
- src/common/navigation/al-locator.types.ts
- test/common/al-locator.spec.ts
Uncovered an issue where the actingNode resolution for console.alertlogic.com was alway returning null.
This was down to how we try to find matching `keyword` values in the URI, and the default `magma` keyword value is of course not present in the prod URL, so this introduces a special value for magma production
> ENG-0000: fix magma production acting node resolution

- package.json
- src/common/navigation/al-locator.types.ts
Uses the US TLD for UK domains.  Differentiation is provided by the
specific domain name rather than the .co.uk.
Fixes many defects and potential defects (hopefully)
> ENG-0000 - Production Staging UK

- package.json
- src/common/errors/al-error.types.ts
- src/common/navigation/al-navigation.types.ts
- src/common/navigation/al-route.types.ts
- src/common/utility/al-trigger.types.ts
Adds support for conditionally enabled routes within a route hierarchy.
Routes that are disabled cannot be activated or made visible, and their
children are ignored.
> ENG-40660 - Support Transitional Navigation

- package.json
- src/client/al-api-client.ts
- src/client/events/index.ts
`AlDefaultClient` now emits an event to its notification stream in the
case of API errors.
> ENG-0000 - Event for API Errors

- package.json
- src/client/al-api-client.ts
The code for encrypting the username and password to base64 was generating invalid `Basic authorization` tokens when the £ character was used in passwords. 
The string should have been put through `unescape(encodeURIComponent(data))` first but it wasn't. When used in a browser the code used `btoa` directly. The non-browser code does use `unescape(encodeURIComponent(data))` and correctly generates the `Basic authorization` token.
Will therefore just remove the usage of btoa and use the base64js code instead. This code would be called outside of a browser environment.
> VTT-4934 btoa issue

- .gitignore
- package.json
- ps_spec.yml
- src/common/cardstack/al-cardstack-view.ts
- test/common/al-cardstack.spec.ts
[ENG-48510](https://alertlogic.atlassian.net/browse/ENG-48510)
This pull request adds a new optional parameter called "resetActiveFilters" to the "updateActiveFilters" function in order to enable resetting active filters when applying a new one.
When "resetActiveFilters" is set to true, the function will clear all filters selected in the same category as the one being applied, leaving only the new filter active. This behavior ensures that only one filter per category is applied at a time.
The implementation includes updating the active filter values and setting the corresponding flags for the affected property and value descriptors.
This feature could be useful in scenarios where users want to refine their search results by applying multiple filters, but only one per category.
> ENG-48510 - dd support for single selection per category in the al-cardstack component

- package.json
- src/common/cardstack/al-cardstack-view.ts
[ENG-48511](https://alertlogic.atlassian.net/browse/ENG-48511)
This pull request adds a new function called `setDefaultFiltersByParams` to allow setting active filters based on query parameters. The function takes a dictionary of query parameters and compares them to the filterable characteristics defined in the cardstack. If there is a match, it applies the active filters to the cardstack.
This function is useful for when users share deeplinks that contain filter parameters, as it will automatically apply those filters when the page is loaded.
> ENG-48511 - Add setDefaultFiltersByParams function to allow setting active filters based on query parameters

- lib/nucleus/src/session/al-authentication.utility.ts
- lib/nucleus/src/session/al-session.ts
- package.json
The current auth token was overwriting the one being inquired about, causing confusion when changing working accounts in e2e test suites.
> ENG-0000 - Fixed token info endpoint

- lib/configuration/src/exclusions/types/index.ts
- lib/reporting/src/responder/types/playbookTypes.ts
- package.json
Const enums are evaluated entirely at compile time, which makes sense for an application (where the values are implicitly inlined) but NOT for a library (in which case the declaration suggests the enum exists, but it is not emitted into the compiled javascript).
> ENG-0000 - Removed const enums

- lib/platform-browser/src/al-conduit-client.ts
- package.json
To avoid breaking internal SSO until it can be transitioned in a coordinated way.
> ENG-0000 - Rolled Back Conduit Base URL

- lib/nucleus/src/common/types/al-locator.types.ts
- lib/nucleus/src/context/al-execution-context.ts
- package.json
- tests/common/al-locator.spec.ts
So that it works as it did before the refactor.  The location matrix (AlLocatorMatrix, now a child of AlExecutionContext) maintains the current state of which datacenter the user is currently working with, and correlates defender and insight location identifiers.  The refactor inadvertantly caused this state not to be persisted as expected.
Appropriately, the region of code where this work happens is labelled with a warning comment (e.g., "watch out for black magic, kids") from the distant past.
> ENG-0000 - Fix Location Resolution

- lib/nucleus/src/client/al-base-api-client.ts
- package.json
Older requests used this property instead of 'credentialed', and the base API client needs to respect both.
> ENG-0000 - Fix 'withCredentials' property
