alertlogic/nepal-core

package.json, src/common/cardstack/al-cardstack-view.ts
[Rally](https://rally1.rallydev.com/#/340101526180d/detail/userstory/385640940492)
=> US116155 - Fix the scroll down is unchecking the cards

package.json, src/aims-client/aims-client.ts
Nepalizing portero (missing endpoint in nepal)
=> ENG-3124: Nepalizing portero (missing endpoint in nepal)

package.json, src/aims-client/aims-client.ts, src/aims-client/types/types.ts
Missing endpoint to create user with details
=> ENG-3124: Nepalizing portero (missing endpoint)

package.json, src/aims-client/aims-client.ts
Aims missing endpoints in nepal
=> ENG-3297: Aims missing endpoints in nepal

package.json, src/aims-client/aims-client.ts, src/aims-client/types/types.ts
Adding missing field to nepal library
=> ENG-3124: Adding missing field to nepal library

package.json, src/aims-client/aims-client.ts, src/aims-client/types/types.ts
- Missing mfa enrollment endpoint in nepal
- Moving the totp class to types
=> ENG-3584: Missing mfa enrollment endpoint in nepal

src/session/utilities/al-session-detector.ts
Cannot read property 'accessToken' of undefined
=> ENG-0000: Cannot read property 'accessToken' of undefined

package.json, src/client/al-api-client.ts
Added convenience methods for GET, POST, PUT, and DELETE that resolve
with the entire response descriptor, not just its deserialized payload.
Also added some basic documentation at the type of the client.
Also restructured the code to keep all of the convenience methods
together.
=> ENG-5563 - AlAPIClient Enhancement

package.json, src/client/al-api-client.ts, src/client/types/index.ts, src/session/al-session.ts
Corrected logic around access token addition, including the ability to
override presence or absence of the header.
=> ENG-0000 - Fixed Broken Access Token logic

src/subscriptions-client/types/al-subscription.types.ts
ENG-5568 - Adding new fim entitlement
=> ENG-5568 - Adding new fim entitlement

package.json, src/common/locator/al-route.types.ts
Adjusts the way visibility is inflected by anonymous state and isPublic
route properties.
=> ENG-4788 - Fix isPublic/anonymous calculations

package.json, src/client/al-api-client.ts, src/session/al-session.ts
Also, add `al.session.expireIn()` convenience method
=> ENG-9999 - Fix prepare() ambiguity

src/client/al-api-client.ts, src/common/utility/al-cabinet.ts
- Updated AlCabinet to support delayed sync (minimizes calls to
JSON.stringify())
- Updated AlApiClient to remove `log()` method (replaced with explicit
check for verbosity + console.log(), minimizes unnecessary interpolation and calls to
JSON.stringify
- Added persistent caching of endpoints data
=> ENG-0000 - Incremental Improvements

package.json, src/common/forms/types.ts
[Jira](https://alertlogic.atlassian.net/browse/ENG-14255)
=> ENG-14255 - Add disabled property in AlDynamicFormControlElementOptions

package.json, src/common/locator/al-navigation.types.ts
Added a whitelist of primary accounts to the experience flag descriptor
type.
=> ENG-14108 - Welcome Page Support

package.json, src/subscriptions-client/types/al-subscription.types.ts
ENG-000 - Adding 'dashboard_authentication' and 'dashboard_firewall' to KnownEntitlements
=> ENG-000 - Adding 'dashboard_authentication' and 'dashboard_firewall' to KnownEntitlements

package.json, src/search-client/search-client.v2.ts, src/search-client/search-stylist-client.ts
**For support Internet Explorer and angular9**
see reference: https://github.com/alertlogic/nepal-client-libs/commit/785286ae3e40570bf5d30ac717350685ef82fe23#diff-527b031ee82cc547cec982780ce1f523R42
=> ENG-000 - Adding 'service_stack' property to search client v2 and search stylist

package.json, src/common/locator/al-location.dictionary.ts, src/common/locator/al-locator.types.ts, src/session/al-session.ts
[Jira](https://alertlogic.atlassian.net/browse/ENG-18472)
=> ENG-18472 - Adding distributor location

package.json, src/common/locator/al-location.dictionary.ts
=> ENG-0000 - Added production distributor API endpoint

package.json, src/session/al-session.ts
Fixes critical issue with account resolution for acting account !=
primary account.
=> ENG-0000 - v1.0.86 fix account resolution

karma.conf.js, package.json, src/client/index.ts, src/client/types/index.ts, src/common/locator/al-navigation.types.ts, src/session/utilities/al-segment-client.ts, src/subscriptions-client/types/al-subscription.types.ts, test/aims-client/aims-client.spec.ts, test/error-handler/al-error-handler.spec.ts, test/search-client/search-client.spec.ts, test/session/al-session.spec.ts
- Added unit test to verify that account resolution properly respects
difference between primary and acting account
- Added some more unit tests in places where coverage was weak
- Gutted the segment client, which is deprecated
- Nicened up some authentication tests
=> ENG-19192 - Critical Unit Tests

package.json
Forces republishing with tv4 validation changes.
=> ENG-0000 - version 1.0.91

package.json, src/common/cardstack/types.ts
[Jira](https://alertlogic.atlassian.net/browse/ENG-20742)
=> ENG-20742 - Add total property to AlCardstackValueDescriptor

.npmrc, package-lock.json
This allows dependabot to correctly determine vulnerabilities based on dependency version.
=> Enabled lockfile and added initial package-lock.json

package.json, src/common/cardstack/types.ts
[Jira](https://alertlogic.atlassian.net/browse/ENG-21454)
=> ENG-21454 - Issues with filter panel

package.json
=> ENG-0000 - Session Idle Timeout (2)

package.json, src/client/al-api-client.ts, src/client/types/index.ts
I don't know why she swallowed the fly...
=> ENG-0000 - support MDR API path prefix

package-lock.json, package.json, src/session/utilities/al-session-detector.ts, test/session/al-session-detector.spec.ts
Prevents overlapping session detection routines from colliding and
causing overwrite of acting account.
Version 1.0.114.
=> ENG-0000 - Session Detection Overlap Defect

package.json, src/common/navigation/al-location.dictionary.ts, src/session/utilities/al-session-detector.ts
Correct the way that auth0 sessions are ingested.
=> VTT-2679 - Okta/SSO Login Misbehavior

package-lock.json, package.json, ps_spec.yml, src/common/navigation/al-location.dictionary.ts, src/session/utilities/al-session-detector.ts, tsconfig.json
Angular7-compatible version of 1.0.118 @al/core.
=> 1.1.0-ng7.1

package-lock.json, package.json, ps_spec.yml, src/session/utilities/al-session-detector.ts, tsconfig.json
This reverts commit dea2601c4193005dd1ba1f52cdd852233d5a10be.
=> Revert "1.1.0-ng7.1 (#141)"

package.json, src/client/al-api-client.ts, src/session/utilities/al-conduit-client.ts
- Added a `ready()` promise to `AlConduitClient`
- Corrected `mfa_code` to `mfaCode` in gestalt authentication via MFA
=> ENG-0000 - Tweaks

package.json, src/aims-client/aims-client.ts, src/client/al-api-client.ts, src/session/utilities/al-authentication.utility.ts, src/session/utilities/index.ts
1.  Adds an AlAuthenticationUtility which collapses direct/gestalt
authentication logic and state management into a single place.
2.  Added support for detecting TOS requirements from AIMS
authentication attempts.
3.  Bumped version to 1.0.130.
=> ENG-27405 - Terms of Service Workflow

package.json, src/configuration/al-runtime-configuration.ts, src/session/utilities/al-authentication.utility.ts, src/session/utilities/al-conduit-client.ts, test/session/al-authentication.utility.spec.ts, test/session/al-conduit-client.spec.ts
To avoid Major Innovations.
Also, adds unit tests around AlAuthenticationUtility.
=> ENG-0000 - Fix Incorrect MFA Enrollment Handling

package.json, src/client/al-api-client.ts
Added logic to set withCredentials for API calls to GestaltAPI and
LegacyUI/ConvergenceAPI.
=> ENG-28315 - withCredentials Normalization (Pass II)

package.json, src/common/navigation/al-route.types.ts
Added placeholder properties for locations and primaryLocations in
`AlRouteCondition`.
=> ENG-29323 - Location Awareness in Navigation

package.json, src/common/forms/types.ts
Just to tide me over until Kevins nepal-ng-forms refactor comes into being
=> ENG-0000: interface update

package.json, src/common/navigation/al-route.types.ts, src/configuration/al-runtime-configuration.ts
- Added regex cache to avoid recompilation of regexps on every menu
refresh cycle
- Added refresh state utility class to avoid redundant string slicing &
dicing
- Added diagnostic mode for AlRoute activation, controlled by
AlRuntimeConfiguration
- Added a convenience method to enable local content mode
=> ENG-0000 - Navigation Diagnostics/Performance Improvements

package.json, src/common/navigation/al-location.dictionary.ts, src/common/navigation/al-locator.types.ts
Added magma to list of locations.
=> ENG-0000 - Magma UI Node

package.json, src/common/cardstack/al-cardstack-view.ts
[Jira](https://alertlogic.atlassian.net/browse/ENG-32133)
=> ENG-32313 - Allow number array in dateRange

package.json, src/common/navigation/al-locator.service.ts, src/common/navigation/al-navigation.types.ts, src/common/utility/al-globalizer.ts, src/configuration/al-runtime-configuration.ts
Supports authentication in cypress.
=> ENG-0000 - Allow Disabling of Strict Collision Handling

package.json, src/common/navigation/al-locator.service.ts, src/common/utility/al-globalizer.ts, src/configuration/al-runtime-configuration.ts
Because sometimes the minimalist hack is better than the verbose,
byzantine "right" way.
=> ENG-0000 - Revert CollisionHandling, detect Cypress

package.json, src/client/al-api-client.ts, src/client/types/index.ts, test/client/al-api-client.spec.ts, test/common/al-cardstack.spec.ts, test/session/al-conduit-client.spec.ts
Updates AlDefaultClient to better support the use of the generic MDR API
location while retaining endpoints support.
Also cleaned up some noisy tests.
=> ENG-0000 - MDR API Support (v1.0.166)

package.json, src/subscriptions-client/subscriptions-client.ts
[ENG-29912](https://alertlogic.atlassian.net/browse/ENG-29912)
=> ENG-29912 - Adding optional query params for the get entitlements method

package-lock.json, package.json, src/common/navigation/al-locator.types.ts
Replaced Robert's nasty, dirty, untranspilable use of a condition spread
operation.  The replacement is less cool for sure, but doesn't cause
other repositories to choke up.
=> ENG-0000 - Conditional Spread Replacement

package.json, src/client/al-api-client.ts, src/session/utilities/al-authentication.utility.ts
US - https://alertlogic.atlassian.net/browse/ENG-32733
=> ENG-32733 - Adding Re-accept workflow

package.json, src/session/utilities/al-authentication.utility.ts
US - https://alertlogic.atlassian.net/browse/ENG-35646
=> ENG-35646 - Adding Deferral Behavior

package.json
=> ENG-0000 - Publish New Client

package.json, src/session/al-session.ts
[ENG-40456](https://alertlogic.atlassian.net/browse/ENG-40456)
=> ENG-40456: Improving AIMS token expiration detection

.gitignore, api-extractor.base.json, index.ts, lib/incidents/src/iris/types/elaboration-event.class.ts, lib/incidents/src/iris/types/elaboration-log.class.ts, lib/incidents/src/iris/types/elaboration.class.ts, lib/nucleus/src/context/al-execution-context.ts, package-lock.json, package.json, rollup.config.js, scripts/buildEntryPointPackages.ts, tsconfig.json, tsconfig.lib.json
Got .d.ts type rollups working as expected (I think), although it required micromanaging the api-extractor tool to work around its implicit assumption that there is a single entry point.
=> ENG-0000 - Type Rollups

package.json, rollup.config.js, scripts/buildEntryPointPackages.ts
Because jest chokes on esm and nothing is every really easy
=> ENG-0000 - Added commonjs variants

package.json
=> ENG-0000 - Added cardstack types for package.json

lib/assets/src/assets-query/types/assets/phoenix-topology-snapshot.class.ts, lib/reporting/src/dashboards/types/index.ts, package.json
@al/dashboards (now @al/core/reporting)
@al/assets-query (not @al/core/assets)
=> ENG-0000 - Imported Latest client changes

lib/assets/src/assets-query/assets-utilities.ts, lib/defender/src/convergence-utility/convergence-utility-client.ts, lib/defender/src/convergence-utility/types/index.ts, lib/nucleus/src/common/errors/index.ts, lib/nucleus/src/session/al-session.ts, package.json
API Client changes
Slight clarification of AlError's second and third optional parameters
=> ENG-0000 - Incremental Enhancements

lib/platform-node/src/al-node-execution-context.ts, lib/platform-node/src/axios-wrapper.ts, lib/platform-node/src/index.ts, lib/platform-node/src/public_api.ts, package.json, rollup.config.js
=> ENG-0000 - Added node platform entry point

lib/platform-node/src/al-node-execution-context.ts, package.json
=> ENG-0000 - Add Proper Base64 codec for node execution context

lib/nucleus/src/session/al-authentication.utility.ts, package.json, rollup.config.js, tsconfig.json
=> ENG-0000 - Change Target to avoid optional chaining issues in consumers

lib/assets/src/assets-query/al-assets-query-client.ts, lib/assets/src/assets-query/types/assets/index.ts, lib/assets/src/assets-query/types/assets/topology-node.class.ts, lib/assets/src/assets-query/types/index.ts, lib/defender/src/convergence-utility/types/index.ts, lib/incidents/src/aecontent/aecontent-client.ts, lib/incidents/src/aecontent/index.ts, lib/incidents/src/aecontent/types/aecontent-client-tuning.type.ts, lib/incidents/src/aecontent/types/index.ts, lib/platform-browser/src/al-conduit-client.ts, lib/reporting/src/connectors/al-connectors-client.ts, lib/reporting/src/connectors/types/integrationsTypes.ts, lib/reporting/src/herald/types/heraldTypes.ts, package-lock.json, package.json
Well, not really scads; but some important ones!
=> ENG-0000 - Incorporated Scads of Updates

lib/platform-browser/src/al-conduit-client.ts, package.json
Wasn't respecting environment normalization
=> ENG-0000 - Fix Bad URL Calculation

lib/nucleus/src/common/types/al-locator.types.ts, lib/nucleus/src/context/al-execution-context.ts, lib/nucleus/src/session/al-session.ts, lib/support/src/gestalt/types/notifications/al-gestalt-notifications-client-interface.ts, package.json
To allow contextual data to be accreted during session bootstrap
=> ENG-0000 - Another Locator Context Fix

lib/nucleus/src/common/errors/index.ts, lib/nucleus/src/common/types/al-locator.types.ts, lib/nucleus/src/context/al-execution-context.ts, lib/nucleus/src/session/al-session.ts, package.json, tests/common/al-locator.spec.ts
Attempting to see if this remedies previously seen failure cases. Bumps version to 2.1.0-beta.1.
=> ENG-0000 - Exploratory Bootstrap Modification

package.json, src/session/al-session.ts, src/session/utilities/al-authentication.utility.ts
- Removes explicit authentication process for fortra sessions
- Adds logic to use Bearer tokens for Fortra-based sessions
=> ENG-50533 - Fortra Token Passthrough

package.json
=> ENG-0000 - Update Version back to V2.1/beta
